spring:
  redis:
    host: localhost
    password: 111222
    port: 6379
    database: 0
    timeout: 6000
    lettuce:
      pool:
        max-active: 10
        max-idle: 1
        max-wait: -1
        min-idle: 1